### ISSUE TITLE
An error need help

### ISSUE THREAD

**Issue by PDWR** [persianhydra/Xeexe-TopAntivirusEvasion#1]
hey,bro. I wanna to test ur project,but i have an error, maybe need ur help, please!
![image](https://user-images.githubusercontent.com/31816249/85117055-d3dfaa80-b250-11ea-818d-56afd9d86c78.png)

**Comment by persianhydra** [comment]
Hi you should use python3
Python3 Xeexe.py

**Comment by shepardac** [comment]
Having same issue, using python3

**Comment by The-Mer0vingian** [comment]
Same issue with Python3.
System up to date.

**Comment by PDWR** [comment]
> Same issue with Python3.
> System up to date.

Using kali linux is good to runing

**Comment by The-Mer0vingian** [comment]
> 
> 
> > Same issue with Python3.
> > System up to date.
> 
> Using kali linux is good to runing

Im using Kali
