### ISSUE TITLE
No such file or directory in ./result/Xeexe.raw

### ISSUE THREAD

**Issue by merlin123h** [persianhydra/Xeexe-TopAntivirusEvasion#16]
Hi.
When i want to install and use this tool, the error which is shown in the attached picture, occurs.
"""[Errno 2] No such file or directory: './result/Xeexe.raw'"""
this is the text of that error message.
please help me to solve this error.
thanks.
![3333](https://user-images.githubusercontent.com/67941449/106435022-2c9e3500-6427-11eb-9b6b-7edc99fe0960.PNG)

**Comment by CYBERDEVILZ** [comment]
Hi merlin123h

It is clear from the error at the 5th line that you do not have msfvenom installed in your system. Hence it is not able to generate the raw payload. And hence it cant find the file. That is why the error pops up at 7th line saying "No such file or directory".

You have to install msfvenom to correct the issue.

As mentioned by the author, kindly run the install.sh file. It will tell you what all files are missing in your system.

**Comment by persianhydra** [comment]
...
