### ISSUE TITLE
can`t run py file

### ISSUE THREAD

**Issue by HEXING19** [persianhydra/Xeexe-TopAntivirusEvasion#19]
can`t run py file

when i run this file

root@ubuntu:/home/Xeexe-TopAntivirusEvasion# python3 Xeexe.py 
 
  File "Xeexe.py", line 43
    _print_base = lambda message, prefix, colour : f"{colour}{colour_codes['RESET_ALL']} {message}"
       

can you help me

**Comment by persianhydra** [comment]
wrong use
