### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PinkPantherX** [persianhydra/Xeexe-TopAntivirusEvasion#4]
I am having this error when runing Xeexe.py :  
File "Xeexe.py", line 195
    while generate_manifest:= input(print_query("Do you want to add Manifest (Generally Bypasses Windows Defender)? (y/n) ")).lower().strip():
                            ^
SyntaxError: invalid syntax

**Comment by persianhydra** [comment]
hi use python3 xeexe.py

**Comment by PinkPantherX** [comment]
Hi, I am using python3 xeexe.py command, but the error occurs.
