### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jepunband** [persianhydra/Xeexe-TopAntivirusEvasion#6]
hi, getting this error:

[+] Creating [./result] directory for resulting code files
/usr/share/metasploit-framework/lib/msf/core/modules/metadata/obj.rb:168: [BUG] Segmentation fault at 0x36ea526c
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [arm-linux-gnueabihf]

and at the end of the process .. i get this :

Aborted
[!] Could not open or read file [./result/Xeexe.raw]
[Errno 2] No such file or directory: './result/Xeexe.raw'

**Comment by persianhydra** [comment]
fix

**Comment by merlin123h** [comment]
hi. getting this error too.
please see picture
![xee](https://user-images.githubusercontent.com/67941449/93437253-9eaf1c80-f880-11ea-99a0-d7649a246dc7.PNG)
