### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by G1ft3dC0d3** [persianhydra/Xeexe-TopAntivirusEvasion#9]
![image](https://user-images.githubusercontent.com/52042546/94988642-06e34b00-056f-11eb-9eab-58b185da79c2.png)

![image](https://user-images.githubusercontent.com/52042546/94988652-1a8eb180-056f-11eb-98a8-2addda06496c.png)

![image](https://user-images.githubusercontent.com/52042546/94988705-7f4a0c00-056f-11eb-9560-c915d6d8c43b.png)

I executed the payload generated by your tools, on a Windows 10 machine x64 bits, on the same subnet... but no session created and the process exited...

**Comment by Akmaling** [comment]
I had same issue on windows 10...

**Comment by persianhydra** [comment]
no problem !!! try again
